### ISSUE TITLE
Add support for encrypted traffic

### ISSUE THREAD

**Issue by lautriv** [secabstraction/PowerCat#3]
Would love to see support for encrypted traffic, maybe something similar to [Cryptcat](http://cryptcat.sourceforge.net/info.php).

**Comment by secabstraction** [comment]
So I've already started doing the reading for this and it is possible to add encryption. However, it won't be compatible with CryptCat as that uses the twofish algorithm. I don't see any providers for twofish in Windows. It should work with Ncat's --ssl option if you know the common name (CN) of the certificate used with the Ncat listener (server). Otherwise, PowerCat-to-PowerCat connections should work great. I'll start a new branch for this ASAP.

**Comment by secabstraction** [comment]
So I added SSL to the TCP transport. Would you mind testing it and letting me know if it's working for you? You'll have to pull from the SSL branch, I haven't accepted it to master yet.

**Comment by secabstraction** [comment]
I went ahead and pulled the SSL branch to master. Please let me know if it's not working.
